# Generated by Django 4.2.3 on 2023-07-10 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0002_employeedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50)),
                ('wk', models.CharField(max_length=50)),
                ('gp', models.CharField(max_length=50)),
                ('nmc', models.CharField(max_length=100)),
                ('indate', models.CharField(max_length=50)),
                ('outDate', models.CharField(max_length=50)),
                ('servicableber', models.CharField(max_length=50)),
                ('fault', models.CharField(max_length=50)),
                ('doc', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('doj', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Components',
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
