# Generated by Django 4.2.3 on 2023-07-10 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0003_employeedetail_delete_components_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='fault',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='indate',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='info',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='nmc',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='outDate',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='servicableber',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='wk',
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50, null=True)),
                ('wk', models.CharField(max_length=50, null=True)),
                ('gp', models.CharField(max_length=50, null=True)),
                ('nmc', models.CharField(max_length=100, null=True)),
                ('indate', models.CharField(max_length=50, null=True)),
                ('outDate', models.CharField(max_length=50, null=True)),
                ('servicableber', models.CharField(max_length=50, null=True)),
                ('fault', models.CharField(max_length=50, null=True)),
                ('doc', models.CharField(max_length=50, null=True)),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('info', models.CharField(max_length=50, null=True)),
                ('doj', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
