# Generated by Django 4.2.3 on 2023-07-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_remove_employeedetail_doc_remove_employeedetail_doj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='fault',
            new_name='flt',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='indate',
            new_name='idt',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='info',
            new_name='ifo',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='nmc',
            new_name='nm',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='outDate',
            new_name='odt',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='remarks',
            new_name='rm',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='servicableber',
            new_name='sbr',
        ),
    ]
