# Generated by Django 4.2.3 on 2023-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_rename_fault_component_flt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='doc',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='doj',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='idt',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='odt',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
